AZURE_OPENAI_API_KEY: "84ebdf1e0e7541d7921c433a47c4374c"
AZURE_OPENAI_ENDPOINT: "https://gptopt.openai.azure.com/"
AZURE_OPENAI_DEPLOYMENT_NAME: "optevus-gpt"
AZURE_OPENAI_API_VERSION: "2024-12-01-preview"